### ISSUE TITLE
The License is unclear about individual pieces of code

### ISSUE THREAD

**Issue by pakoito** [flibitijibibo/RogueLegacy1#1]
After reading through the license it is unclear to me whether I can take some pieces of code from, say, the Input Manager, and use them to create a classic 2D platformer about a hungry purple demigod ball. Even if the source is available for learning purposes, if the license is not clear enough it can be constructed that any code I write that is inspired by it is not a clean room implementation, and thus breaching the license.

**Comment by flibitijibibo** [comment]
I can clear this up: you're definitely welcome to write your own stuff that takes inspiration from RL1, just don't _directly_ copypaste anything - peeking at the source from time to time while you're writing something else is totally okay.

**Comment by a2937** [comment]
So like if someone totally wanted to, they could totally take inspiration from this code and try to recreate the logic in a free open source game engine that is named for a famous play and release the result for free on Github?

**Comment by pakoito** [comment]
> I can clear this up: you're definitely welcome to write your own stuff that takes inspiration from RL1, just don't _directly_ copypaste anything - peeking at the source from time to time while you're writing something else is totally okay.

Makes sense. At fintech companies I've been stopped by legal before I read through copyrighted code due to those "clean room" nuances. I believe it'll be okay as inspiration for personal projects and such :D

**Comment by flibitijibibo** [comment]
> So like if someone totally wanted to, they could totally take inspiration from this code and try to recreate the logic in a free open source game engine that is named for a famous play and release the result for free on Github?

Definitely - the important part of the release is the sharing of _ideas_; we can hold a copyright on the code but we won't/can't assert ownership of the ideas the code implements.
