### ISSUE TITLE
Building and running the project on MacOS M1

### ISSUE THREAD

**Issue by wihu** [flibitijibibo/RogueLegacy1#4]
I am able to build the project following the instructions, however, when running the project, I am getting an error:
```
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'RogueCastle.Program' threw an exception. ---> System.DllNotFoundException: libSDL3.0.dylib
```
I realised there are no pre-built libs for MacOS in the `fnalibs3` package, I tried to look for the libs on the web, but could not find anything that are compatible, maybe I should build them myself, but is this even possible/supported?

**Comment by flibitijibibo** [comment]
We actually _just_ started experimenting with automated builds this week; you can find them here:

https://github.com/FNA-XNA/fnalibs-dailies/actions

If something breaks let us know, I pushed a Steam build that seems to work but I don't have arm64 hardware to check with.

**Comment by wihu** [comment]
Wow, it worked like a charm! Although, I can only run it with:
```
mono RogueLegacy.exe
```
instead of
```
dotnet RogueLegacy.exe
```
Getting another error:
`A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '~/Projects/RogueLegacy1/RogueCastle/bin/x64/Debug/net40/'`

Not sure what's the difference, but at least I can run the game now. Thank you!

**Comment by flibitijibibo** [comment]
That's about right, we only support Mono right now. Glad it works!
