### ISSUE TITLE
Missing Shaders sources

### ISSUE THREAD

**Issue by wihu** [flibitijibibo/RogueLegacy1#5]
I understand that Shaders is part of the game assets/content, but they are packaged in xnb format, which is difficult to decompile if not impossible. Is it possible that the Shaders source codes are also made available? For the purpose of learning how things/effects get rendered in the game.

**Comment by flibitijibibo** [comment]
Good idea, will talk to Kenny about this soon.

**Comment by flibitijibibo** [comment]
Should have these in the repo tomorrow morning!

**Comment by wihu** [comment]
> Should have these in the repo tomorrow morning!

That's awesome, thank you!

**Comment by flibitijibibo** [comment]
This is now live!

https://github.com/flibitijibibo/RogueLegacy1/tree/main/RogueCastle/Shaders
